In [23]:
import numpy as np

a = np.array([[0,10,20],[1,11,21], [2,12,22], [3,13,23]])
a

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23]])

In [24]:
def make_flat(x):
    return x.T.flatten()
def make_rect(x, Nrows, Ncols):
    return x.reshape((Ncols, Nrows)).T

In [25]:
af = make_flat(a)
af

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23])

In [26]:
Ncols = a.shape[1]
Nrows = a.shape[0]

# af.reshape((Nrows, Ncols)).T
make_rect(af, Nrows, Ncols)

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23]])