In [23]:
import numpy as np

a = np.array([[0,10,20],[1,11,21], [2,12,22], [3,13,23]])
a

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23]])

In [24]:
def make_flat(x):
    return x.T.flatten()
def make_rect(x, Nrows, Ncols):
    return x.reshape((Ncols, Nrows)).T

In [25]:
af = make_flat(a)
af

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23])

In [26]:
Ncols = a.shape[1]
Nrows = a.shape[0]

# af.reshape((Nrows, Ncols)).T
make_rect(af, Nrows, Ncols)

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23]])

In [32]:
a = np.zeros((1, 10))
b = np.zeros((1, 10))
for i in range(0,10):
    a[0,i] = i
    b[i] = i

IndexError: index 1 is out of bounds for axis 0 with size 1

In [31]:
print a
print b
print a.shape, b.shape

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]]


NameError: name 'b' is not defined

In [30]:
a.shape

(1, 10)